name: Build and deploy Python app to Azure Web App - python-api2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Create virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create startup script
        run: |
          echo "cd /home/site/wwwroot" > startup.sh
          echo "python -m venv antenv" >> startup.sh
          echo "source antenv/bin/activate" >> startup.sh
          echo "pip install -r requirements.txt" >> startup.sh
          echo "uvicorn main:app --host 0.0.0.0 --port 8000" >> startup.sh
          chmod +x startup.sh
          
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "*.git*" "*.github*"
          
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: Unzip artifact for deployment
        run: unzip release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1A91B1DAA50F4C008A96E61D057FF4D4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5AB01C6F0D494607B02DE94546344BD7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8CE3670B7CD04093BD2C8D9B83E27A7B }}
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'python-api2'
          slot-name: 'Production'
          startup-command: './startup.sh'
